version: '3.3'
services:
  postgres:
    restart: always
    build: .
    container_name: 'postgres'
    working_dir: '/root/'
    tty: true
    privileged: true
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD='password'
    volumes:
      - .:/app
      - ~/OneDrive:/mnt/OneDrive
    ports:
      - "5432:5432"
      - "23:23"
