version: '3'

services:
  kali:
    build: .
    container_name: 'kali'
    ports:
      - '22:22'
      - '23:23'
    working_dir: '/root/'
    tty: true
    privileged: true
    volumes:
      - .:/app
      - C:\Users\sprin\OneDrive:/mnt/OneDrive
