version: '3'
services:
  mysqldb:
    image: mysql:8.0
    # platform: linux/x86_64
    container_name: 'mysql'
    environment:
    # - MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # - MYSQL_RANDOM_ROOT_PASSWORD
      - TZ='Asia/Tokyo'
    volumes:
      - .:/app
      - ~/OneDrive:/mnt/OneDrive
    ports:
      - "3306:3306"
      - "23:23"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
